### ISSUE TITLE
The library is in violation of Polychrom's licencing terms

### ISSUE THREAD

**Issue by mimakaev** [junioreif/OpenMiChroM#101]
Hi guys, 

I noticed that you copied large chunks of polychrom library, to which I've been the main contributor. 

Polychrom is released under the fairly permissive MIT licence. However, MIT licence does require that you reproduce the copyright message of the original library if you reuse substantial pieces of the codebase. Therefore, your library is legally violating terms of polychrom's MIT licence, and I'm asking you to correct this. 

Moreover, I personally find it very disturbing that you are not attributing polychrom or Open2C in any of the files of the library. While you are not legally required to do so, this is not the best in terms of academic integrity and honesty. 

Best, 
Max

**Comment by contessoto** [comment]
Hello Max,

Thank you for pointing this out. 
We sincerely apologize for the oversight. 
We will ensure the proper mentions/references are included ASAP in the source from which the code was obtained or inspired. 
Please let us know if you have any specific references you would like us to cite or include.

Please feel free to reach out if you have any other concerns.

Best,
Vini

**Comment by mimakaev** [comment]
Hi Vini, 

Thanks for a quick reply! 

It would be sufficient to attribute polychrom and open2C simply using the links to github pages - we do not have a publication for polychrom. If you need to cite it, we have a zenodo DOI for it https://zenodo.org/records/3579473

Max

**Comment by junioreif** [comment]
Hi Max,

I would like to apologize for my oversight.

I have included the citations for Zenodo and the Open2C GitHub page in the new OpenMichrom release (v1.0.9). Its shows at

- The documentation.
- The GitHub page.
- The Header, when the simulation starts.

I want to mention that the part of your code that I've been using is related to output printing. Also, although our code is different, we took some inspiration on how to build the simulation per block. Appropriated citations have been added to the code. 

I apologize again for the oversight. And I will be careful in the future to appropriately refer to your work if I further use it.

Thanks for your understanding. Please don't hesitate to contact me if you have any further concerns.

Best regards,
Antonio
