### ISSUE TITLE
Default platform precision 

### ISSUE THREAD

**Issue by ed29rice** [junioreif/OpenMiChroM#26]
Currently, the default precision is set at setup as:

`def setup(self, platform="CUDA", PBC=False, PBCbox=None, GPU="default",
              integrator="langevin", errorTol=None, precision="mixed",deviceIndex="default"):`

But the variable precision is not passed to the platform unless the variable GPU is not "default". This is because here:
`        self.GPU = str(GPU)
        properties = {}
        if self.GPU.lower() != "default":
            properties["DeviceIndex"] = deviceIndex
            properties["Precision"] = precision
        self.properties = properties`

The variable self.properties will be empty if str(GPU) is default. If self.properties is empty, then the precision is set to the platform default which is single. 
Then, there is a mismatch on what is the default precision of the platform.

**Comment by contessoto** [comment]
I am closing this because the issue was solved in the last commit by ed29rice
