### ISSUE TITLE
Wrong MODEL writing PDB file

### ISSUE THREAD

**Issue by contessoto** [junioreif/OpenMiChroM#40]
The fields should foolw:
# pdb formats              1         2         3
#                 123456789012345678901234567890
model          = "MODEL     {0:4d}"
atom           = "ATOM  {0:5d} {1:^4s}{2:1s}{3:3s} {4:1s}{5:4d}{6:1s}   {7:8.3f}{8:8.3f}{9:8.3f}{10:6.2f}{11:6.2f}          {12:>2s}{13:2s}"
ter            = "TER   {0:5d}      {1:3s} {2:1s}{3:4d}{4:1s}"

https://github.com/Matheus-Mello/NDB-Converters/blob/master/ndb2pdb.py

**Comment by mellofariam** [comment]
Fixed in the last version.
