### ISSUE TITLE
set force group

### ISSUE THREAD

**Issue by s-brahmachari** [junioreif/OpenMiChroM#52]
Have the option to *set* force_group when creating the force object. Currently, '_apply_forces' overrides the force_group assignment.

**Comment by s-brahmachari** [comment]
-have the option to assign a force group when creating the force
-inside _applyForces function:
         -check if all the force objects have been assigned groups, else assign them a number not already in the forgeGroup list
         -if more than 32 assign, the force a number X

**Comment by contessoto** [comment]
@s-brahmachari , I believe this is now fixed in version 1.0.7, right?

**Comment by s-brahmachari** [comment]
well..kind of.. but still force groups are handled in a queer way. There is a hard test for the name "Ideal" which is not the ideal way to assign force groups. Is it possible to assign non-zero force groups while defining the force objects? Then assign groups to the  forces that are in the zero group (ie the ones that haven't been assigned when defining) while initializing the system and context...
