### ISSUE TITLE
add converters to cndbTools

### ISSUE THREAD

**Issue by s-brahmachari** [junioreif/OpenMiChroM#53]
the converters should have flags to identify a snippet of the trajectory. 
Given a trajectory of say 1M frames in cndb, one should be able to use the converters to create a .gro/.ndb/.pdb trajectory containing say, 1000 frames starting at t1 and ending at t2, or just one frame.

**Comment by contessoto** [comment]
Just adding that we need to add the newer version of cndb into the code.
-When loading a cndb file, it must check the file version;
-Need to add the converter/encoder from .ndb to cndb.
