### ISSUE TITLE
setFibPosition input changes

### ISSUE THREAD

**Issue by ChristianKKelley** [junioreif/OpenMiChroM#60]
Less of an "issue" and more a technical question.  On the open-michrom.readthedocs.io, one of the input parameters is a tuple called "dist".  This is consistent with the multi-polymer sample simulation.

However, running the script says there is no such parameter.  Looking on the ChromDynamics.py file, I noticed that indeed, no such input param exists for current "setFibPosition".  There is a Nbeads by 3 numpy array (from what I can tell) called "positions".

I'm wondering how to run the sample code, based on this change / if I need to use the positions input instead.

**Comment by contessoto** [comment]
The documentation is now in the latest version: 
https://open-michrom.readthedocs.io/en/latest/OpenMiChroM.html#OpenMiChroM.ChromDynamics.MiChroM.setFibPosition

**Comment by ChristianKKelley** [comment]
I was able to run it!  Thank you
